# Generated by Django 2.2.13 on 2020-09-06 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20200904_1623'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-storage_time']},
        ),
    ]
