# Generated by Django 2.2.13 on 2020-09-07 07:46

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20200906_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
