# Generated by Django 2.2.13 on 2020-09-07 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20200907_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_number',
            field=models.CharField(max_length=30),
        ),
    ]
