# Generated by Django 2.2.13 on 2020-09-09 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_auto_20200907_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='picture',
            field=models.ImageField(default='default_picture', upload_to='books/%Y/%m/%d'),
        ),
    ]
